# ----------------------- #
#      Main Configs       #
# ----------------------- #
baseurl: ""
url: http://euts.github.io
title: Capstone 2
tagline: Effat University Tech Society
email: hamohammed.as@gmail.com
description: About final project

# Team names, titles and social links
people:
- name: Haneen Mohammed
  pic: 1
  position: Member
  social:
    - title: facebook
      url: https://www.facebook.com/public/Haneen-Ashor
    - title: github
      url: https://github.com/haneensa
    - title: linkedin
      url: https://www.linkedin.com/haneenmohammed

- name: Israa Alqassas
  pic: 2
  position: Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Reemaz Hetaimish
  pic: 3
  position: Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #
- name: Sarah Alharathey
  pic: 4
  position: Member
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: /:categories/:title

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/euts
